name: PR Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: |
        gh auth login --with-token < ${{ secrets.GB_TOKEN }}

    - name: Get PR number
      id: get_pr_number
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

    - name: Get PR files
      id: pr_files
      run: |
        PR_NUMBER=${{ env.PR_NUMBER }}
        echo "Fetching files for PR number: $PR_NUMBER"
        FILES=$(gh pr view $PR_NUMBER --json files -q '.files[].path')
        echo "FILES=$FILES" >> $GITHUB_ENV

    - name: Print files changed
      run: echo "Files changed in this PR: ${{ env.FILES }}"
